name: Build images and push (on master branch or on schedule)

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run CI
      run: |
        echo ${{ secrets.DH_PW }} | docker login -u ${{ secrets.DH_USER }} --password-stdin
        docker build -t ppiper/cf-cli:latest .
        docker push ppiper/cf-cli:latest
